dcConsData = [
	{name:"닌바.png",     keywords:["닌바"],                             tags:["닌디보"]},
	{name:"닌하.png",     keywords:["닌하"],                             tags:["닌디보"]},
	{name:"닌바디보.png",     keywords:["닌바디보"],                             tags:["닌디보"]},
	{name:"샌드위치.png",     keywords:["샌드위치"],                             tags:["닌디보"]},
	{name:"디보샤워.png",     keywords:["디보샤워"],                             tags:["닌디보"]},
	{name:"실력차이.png",     keywords:["실력차이"],                             tags:["닌디보"]},
	{name:"안취해따.png",     keywords:["안취해따"],                             tags:["닌디보"]},
	{name:"디보핫하.png",     keywords:["디보핫하"],                             tags:["닌디보"]},
	{name:"닌또죽.png",     keywords:["닌또죽"],                             tags:["닌디보"]},
	{name:"냉장고.png",     keywords:["냉장고"],                             tags:["닌디보"]},
	{name:"털로가득.jpg",     keywords:["털로가득"],                             tags:["짤방"]},
	{name:"오우야.png",     keywords:["오우야"],                             tags:["닌디보"]},
	{name:"디보심심.png",     keywords:["디보심심"],                             tags:["닌디보"]},
];